### ISSUE TITLE
Inserts Tiquets/Domicili

### ISSUE THREAD

**Issue by laasso** [laasso/M02UF2-PE03_DDL#1]
En los inserts para las tablas comandes_domicili i tiquets no estan funcionando.

[Commit referencia #fd818d5
](https://github.com/laasso/M02UF2-PE03_DDL/commit/fd818d53cc3bb8b02b3b82d29b4a553aeea854d3)
Habria que revisar los csv y como estan generados.

El problema parece estar en las relaciones, una posible solucion seria hacer inserts aleatorizados de los id de Referencia 
```shell
-- Taula per a les comandes a domicili
CREATE TABLE comandes_domicili (
    id INT AUTO_INCREMENT PRIMARY KEY,
    adreca_entrega VARCHAR(255),
    temps_estimat TIME,
    valoracio_client INT,
    data_entrega TIMESTAMP,
    FOREIGN KEY (id) REFERENCES tiquets(id)
);

-- Taula per als tiquets
CREATE TABLE tiquets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    client_id CHAR(9),
    treballador_id INT,
    preu_total DECIMAL(10,2),
    data_hora TIMESTAMP,
    FOREIGN KEY (client_id) REFERENCES clients(dni),
    FOREIGN KEY (treballador_id) REFERENCES personal(id)
);

``` 
@Angelfega Podrias Revisarlo?

**Comment by Angelfega** [comment]
Issue solucionada. Lo que pasaba es que la tabla tiquets estaba mal implementada ya que la FK que hacia referencia a empleado no existia ya que anteriormente la remplazamos por sus DNIs. La solución ha sido cambiar estos pequeños fallos en el create
